server.port=8080
spring.application.name=studyroom
spring.thymeleaf.prefix=classpath:/templates/
spring.web.resources.static-locations=classpath:/static/

# ==== PostgreSQL Database (TCP connection to localhost:5432) ====
spring.datasource.url=jdbc:postgresql://localhost:5432/studyroom
spring.datasource.username=postgres
spring.datasource.password=ngochoang
spring.datasource.driver-class-name=org.postgresql.Driver

# ==== JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
